---
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

setup.template.enabled: true
setup.template.name: "filebeat-syslog-%{[agent.version]}"
setup.template.pattern: "filebeat-syslog-%{[agent.version]}-*"
setup.template.overwrite: false

# setup.ilm.enabled: auto
# setup.ilm.rollover_alias: "filebeat-syslog-%{[agent.version]}"
# setup.ilm.pattern: "{now/d}-000001"
# setup.ilm.policy_name: "filebeat-syslog"
# setup.ilm.check_exists: true
# setup.ilm.overwrite: true
setup.ilm.enabled: false

output.elasticsearch:
  enabled: true
  hosts: ["${ELASTIC_HOST}:${ELASTIC_PORT}"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities:
    - "/usr/share/filebeat/certs/ca.crt"
  loadbalance: true
  index: "filebeat-syslog-%{[agent.version]}-%{+yyyy.MM.dd}"
  protocol: https
  ssl.enabled: true

filebeat.inputs:
  - type: syslog
    protocol.udp:
      host: "0.0.0.0:9000"
    tags: ["filebeat_plain_syslog"]

  - type: syslog
    protocol.tcp:
      host: "0.0.0.0:9000"
    tags: ["filebeat_plain_syslog"]
